### PR TITLE
Added filter saturate on icons during hover.

### LINKED ISSUE #4: Saturate icons on hover
The page under tany4.com/social contains several icomoon icons. I would like to make the page more user friendly by increasing the colour saturation of the icons on hover.

So, ideally, the icons would load on something like 60% saturation and on hover set it to 100%.

Feel free to set a different initial saturation value per icon if you think it looks better, or even changing any other filter, not just saturation. Whatever works :)

Good luck and happy hacktoberfest!

### PR DESCRIPTION
**Pull request by mmikaeleriksson**
fix #4 

Started at 40% saturation, made it look like a bit more of a difference than 60%.

### CODE REVIEW

**Comment by altany** [comment]
40% sounds fine but there is an error in your SASS file. Looks like you used CSS syntax and it's failing. Could you please fix this?

**Comment by altany** [comment]
Looks good thanks :)

**Comment by altany** [comment]
I am happy to merge this

**Comment by mmikaeleriksson** [comment]
Looks like it got deleted when I removed my fork.
Made a new request #8 
Maybe you can delete this request

**Pull request closed without merging**
